name = "luminos-crystal-calendar"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Cloudflare Pages 配置
pages_build_output_dir = "out"

# 环境变量
[env.production.vars]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"

# 构建配置
[build]
command = "npm run build:cloudflare"
cwd = "."
watch_dir = "src"

# 路由配置
[[routes]]
pattern = "/api/*"
zone_name = "your-domain.com"
custom_domain = true

# 兼容性设置
[compatibility_flags]
nodejs_compat = true
